version: "3.3"
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:80

  proxy:
    image: testcab/cors-anywhere:0.4.4
    container_name: cors-proxy
    ports:
      - 8888:8080

