version: "3.3"
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  proxy:
    image: yasinuslu/cors-anywhere:latest
    container_name: cors-proxy
    ports:
      - 8888:80

